version: "3.8"
services:
  db:
    container_name: postgres-inventory-service
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: inventory-service
    ports:
      - "5432:5432"